name: ci
on: 
  push:
  pull_request:
  schedule:
    - cron: 0 14 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
      - run: deno run -A dev.ts
